### ISSUE TITLE
Weekly Generator returns java.util.NoSuchElementException: key not found: thursday

### ISSUE THREAD

**Issue by StephenOTT** [cetic/tsimulus-ms#12]
when using a weekly generator the thursday keyword does not appear to work

```
    {
      "name": "weekly-variation",
      "type": "weekly",
		"points": {"thursday": 8.4, "friday": -3.6, "saturday": 9.52, "sunday" : 10.9}
    },
```

**Comment by alexnuttinck** [comment]
Hi @StephenOTT,

Thanks for your bug report,

This bug has been corrected (https://github.com/cetic/TSimulus/commit/fdbe1f942da578a87e2f4db0dd86ffa6f5d2b294) but was has not taken in the last release (0.1.14).

I will create a new release with the correction, and once updated I will close this issue.

**Comment by StephenOTT** [comment]
+1 thanks!  Great tool.  using it with github.com/camunda to generate fake data!

**Comment by alexnuttinck** [comment]
I close this issue. We are now using tsimulus v0.1.18.
