### ISSUE TITLE
Add ability to preform additional data manipulations post generation of time series

### ISSUE THREAD

**Issue by StephenOTT** [cetic/tsimulus-ms#13]
Would be great to have the ability to execute additional manipulations of the time series post generation. Example: removing patterns of days such as Do XYZ manipulation when it is a Weekend or a holiday.  Holidays are easier using Missing Data manipulations, but Weekends are continuous and cumbersome to manually manage..

**Comment by mgoeminne** [comment]
[Tsimulus v0.1.16](https://github.com/cetic/TSimulus/commits/v0.1.16) introduces [DateTime Generators](https://tsimulus.readthedocs.io/en/latest/generators.html#datetime-generators)

You can for instance transform the timestamp associated with any value into the day-of-week, and then check if this value corresponds to a particular day of interest, such as saturday or sunday.
